/**
 * Auto-Tagging Service
 *
 * Automatically tag conversations based on content analysis
 */

import { ChatMessage } from '../../shared/types';
import { HistoryService } from './history';
import { keyPointExtractionService } from './keyPointExtraction';
import { autoCategorizationService } from './autoCategorization';

export interface Tag {
    id: string;
    name: string;
    color?: string;
    category?: string;
}

export interface ConversationTags {
    sessionId: string;
    tags: string[]; // Tag IDs
    autoGenerated: boolean;
    taggedAt: number;
}

// Predefined tag patterns
const TAG_PATTERNS: Array<{
    tag: string;
    patterns: RegExp[];
    category?: string;
}> = [
    {
        tag: 'code',
        patterns: [/\b(code|function|program|script|api|bug|error|debug)\b/i],
        category: 'coding',
    },
    {
        tag: 'question',
        patterns: [/\?/g, /\b(what|how|why|when|where|who|which)\b/i],
    },
    {
        tag: 'tutorial',
        patterns: [/\b(tutorial|guide|how to|step by step|learn|teach)\b/i],
        category: 'learning',
    },
    {
        tag: 'problem-solving',
        patterns: [/\b(problem|issue|fix|solve|troubleshoot|debug)\b/i],
        category: 'technical',
    },
    {
        tag: 'creative',
        patterns: [/\b(write|story|poem|creative|imagine|narrative)\b/i],
        category: 'creative',
    },
    {
        tag: 'analysis',
        patterns: [/\b(analyze|analysis|evaluate|review|compare|assess)\b/i],
        category: 'analysis',
    },
    {
        tag: 'urgent',
        patterns: [/\b(urgent|asap|immediately|critical|important|priority)\b/i],
    },
    {
        tag: 'long-conversation',
        patterns: [], // Applied based on message count
    },
    {
        tag: 'technical',
        patterns: [/\b(technical|implementation|architecture|system|design)\b/i],
        category: 'technical',
    },
    {
        tag: 'beginner',
        patterns: [/\b(beginner|newbie|first time|learning|introduction|basics)\b/i],
        category: 'learning',
    },
];

const isRecord = (value: unknown): value is Record<string, unknown> => (
    typeof value === 'object' && value !== null
);

const parseJson = (raw: string): unknown => {
    try {
        return JSON.parse(raw);
    } catch {
        return null;
    }
};

const sanitizeStringArray = (value: unknown): string[] => {
    if (!Array.isArray(value)) {
        return [];
    }
    return value.filter((entry): entry is string => typeof entry === 'string');
};

const sanitizeCustomTag = (value: unknown): Tag | null => {
    if (!isRecord(value) || typeof value.id !== 'string' || typeof value.name !== 'string') {
        return null;
    }

    return {
        id: value.id,
        name: value.name,
        color: typeof value.color === 'string' ? value.color : undefined,
        category: typeof value.category === 'string' ? value.category : undefined,
    };
};

const parseStoredCustomTags = (raw: string): Tag[] => {
    const parsed = parseJson(raw);
    if (!Array.isArray(parsed)) {
        return [];
    }

    return parsed
        .map((entry) => sanitizeCustomTag(entry))
        .filter((entry): entry is Tag => entry !== null);
};

const sanitizeConversationTags = (value: unknown): ConversationTags | null => {
    if (!isRecord(value)
        || typeof value.sessionId !== 'string'
        || typeof value.autoGenerated !== 'boolean'
        || typeof value.taggedAt !== 'number') {
        return null;
    }

    return {
        sessionId: value.sessionId,
        tags: sanitizeStringArray(value.tags),
        autoGenerated: value.autoGenerated,
        taggedAt: value.taggedAt,
    };
};

const parseStoredConversationTags = (raw: string): ConversationTags[] => {
    const parsed = parseJson(raw);
    if (!Array.isArray(parsed)) {
        return [];
    }

    return parsed
        .map((entry) => sanitizeConversationTags(entry))
        .filter((entry): entry is ConversationTags => entry !== null);
};

export class AutoTaggingService {
    private static instance: AutoTaggingService;
    private readonly STORAGE_KEY = 'conversation_tags';
    private customTags: Map<string, Tag> = new Map();
    private tagsCacheRaw: string | null = null;
    private tagsCacheList: ConversationTags[] = [];
    private tagsBySessionCache: Map<string, ConversationTags> = new Map();
    private sessionsByTagCache: Map<string, string[]> = new Map();

    private constructor() {
        this.loadCustomTags();
    }

    static getInstance(): AutoTaggingService {
        if (!AutoTaggingService.instance) {
            AutoTaggingService.instance = new AutoTaggingService();
        }
        return AutoTaggingService.instance;
    }

    /**
     * Load custom tags from localStorage
     */
    private loadCustomTags(): void {
        try {
            const stored = localStorage.getItem('custom_tags');
            if (stored) {
                const tags = parseStoredCustomTags(stored);
                tags.forEach(tag => {
                    this.customTags.set(tag.id, tag);
                });
            }
        } catch (error) {
            console.error('Failed to load custom tags:', error);
        }
    }

    /**
     * Save custom tags
     */
    private saveCustomTags(): void {
        try {
            const tags = Array.from(this.customTags.values());
            localStorage.setItem('custom_tags', JSON.stringify(tags));
        } catch (error) {
            console.error('Failed to save custom tags:', error);
        }
    }

    /**
     * Auto-tag a conversation
     */
    async tagConversation(sessionId: string): Promise<ConversationTags> {
        const session = HistoryService.getSession(sessionId);
        if (!session || !session.messages || session.messages.length === 0) {
            return {
                sessionId,
                tags: [],
                autoGenerated: true,
                taggedAt: Date.now(),
            };
        }

        const allText = session.messages
            .map(m => m.content || '')
            .join(' ')
            .toLowerCase();

        const matchedTags: string[] = [];

        // Check predefined patterns
        for (const patternGroup of TAG_PATTERNS) {
            if (patternGroup.patterns.length === 0) {
                // Special case: long-conversation
                if (patternGroup.tag === 'long-conversation' && session.messages.length > 20) {
                    matchedTags.push(patternGroup.tag);
                }
                continue;
            }

            const matches = patternGroup.patterns.some(pattern => pattern.test(allText));
            if (matches) {
                matchedTags.push(patternGroup.tag);
            }
        }

        // Extract topics and use as tags
        const extractionResult = keyPointExtractionService.extractKeyPoints(session.messages);
        const topTopics = extractionResult.topics.slice(0, 3);
        topTopics.forEach(topic => {
            // Normalize topic to tag format
            const tagId = topic.toLowerCase().replace(/\s+/g, '-').substring(0, 20);
            if (!matchedTags.includes(tagId)) {
                matchedTags.push(tagId);
            }
        });

        // Get category and add as tag
        const category = autoCategorizationService.getCategorization(sessionId);
        if (category && !matchedTags.includes(category.primaryCategory)) {
            matchedTags.push(category.primaryCategory);
        }

        // Check for action items (tag as 'action-items')
        if (extractionResult.actionItems.length > 0) {
            matchedTags.push('action-items');
        }

        // Check for decisions (tag as 'decisions')
        if (extractionResult.decisions.length > 0) {
            matchedTags.push('decisions');
        }

        const result: ConversationTags = {
            sessionId,
            tags: matchedTags,
            autoGenerated: true,
            taggedAt: Date.now(),
        };

        // Save tags
        this.saveTags(result);

        return result;
    }

    /**
     * Save tags to localStorage
     */
    private saveTags(tags: ConversationTags): void {
        try {
            const allTags = this.readAllTags();
            const index = allTags.findIndex(t => t.sessionId === tags.sessionId);
            if (index >= 0) {
                allTags[index] = tags;
            } else {
                allTags.push(tags);
            }
            const nextRaw = JSON.stringify(allTags);
            localStorage.setItem(this.STORAGE_KEY, nextRaw);
            this.updateTagCaches(allTags, nextRaw);
        } catch (error) {
            console.error('Failed to save tags:', error);
        }
    }

    private updateTagCaches(entries: ConversationTags[], rawValue: string | null): void {
        this.tagsCacheRaw = rawValue;
        this.tagsCacheList = entries;
        this.tagsBySessionCache = new Map(entries.map((entry) => [entry.sessionId, entry]));

        const sessionsByTag = new Map<string, string[]>();
        for (let i = 0; i < entries.length; i++) {
            const entry = entries[i];
            for (let tagIndex = 0; tagIndex < entry.tags.length; tagIndex++) {
                const tag = entry.tags[tagIndex];
                const sessions = sessionsByTag.get(tag);
                if (sessions) {
                    sessions.push(entry.sessionId);
                } else {
                    sessionsByTag.set(tag, [entry.sessionId]);
                }
            }
        }
        this.sessionsByTagCache = sessionsByTag;
    }

    private readAllTags(): ConversationTags[] {
        const stored = localStorage.getItem(this.STORAGE_KEY);
        if (!stored) {
            this.updateTagCaches([], stored);
            return [];
        }
        if (stored === this.tagsCacheRaw) {
            return this.tagsCacheList;
        }

        const parsed = parseStoredConversationTags(stored);
        this.updateTagCaches(parsed, stored);
        return parsed;
    }

    /**
     * Get tags for a session
     */
    getTags(sessionId: string): ConversationTags | null {
        try {
            this.readAllTags();
            return this.tagsBySessionCache.get(sessionId) || null;
        } catch (error) {
            console.error('Failed to load tags:', error);
            return null;
        }
    }

    /**
     * Get a bulk lookup of sessionId -> tags entry
     */
    getTagsLookup(): Map<string, ConversationTags> {
        try {
            this.readAllTags();
            return this.tagsBySessionCache;
        } catch (error) {
            console.error('Failed to load tags lookup:', error);
            return new Map();
        }
    }

    /**
     * Manually add/remove tags
     */
    updateTags(sessionId: string, tags: string[], autoGenerated: boolean = false): void {
        const result: ConversationTags = {
            sessionId,
            tags,
            autoGenerated,
            taggedAt: Date.now(),
        };
        this.saveTags(result);
    }

    /**
     * Get all unique tags across all conversations
     */
    getAllTags(): string[] {
        try {
            const allTags = this.readAllTags();
            const uniqueTags = new Set<string>();
            allTags.forEach(ct => {
                ct.tags.forEach(tag => uniqueTags.add(tag));
            });
            return Array.from(uniqueTags).sort();
        } catch (error) {
            console.error('Failed to load tags:', error);
            return [];
        }
    }

    /**
     * Get conversations by tag
     */
    getConversationsByTag(tagId: string): string[] {
        try {
            this.readAllTags();
            const sessions = this.sessionsByTagCache.get(tagId);
            return sessions ? [...sessions] : [];
        } catch (error) {
            console.error('Failed to load tags:', error);
            return [];
        }
    }

    /**
     * Add a custom tag
     */
    addCustomTag(tag: Tag): void {
        this.customTags.set(tag.id, tag);
        this.saveCustomTags();
    }

    /**
     * Get all custom tags
     */
    getCustomTags(): Tag[] {
        return Array.from(this.customTags.values());
    }
}

export const autoTaggingService = AutoTaggingService.getInstance();
