class InMemoryStorage implements Storage {
  private store = new Map<string, string>();

  get length(): number {
    return this.store.size;
  }

  clear(): void {
    this.store.clear();
  }

  getItem(key: string): string | null {
    return this.store.has(key) ? this.store.get(key)! : null;
  }

  key(index: number): string | null {
    return Array.from(this.store.keys())[index] ?? null;
  }

  removeItem(key: string): void {
    this.store.delete(key);
  }

  setItem(key: string, value: string): void {
    this.store.set(key, value);
  }
}

jest.mock('../src/renderer/services/history', () => ({
  HistoryService: {
    getSession: jest.fn(() => null),
  },
}));

jest.mock('../src/renderer/services/keyPointExtraction', () => ({
  keyPointExtractionService: {
    extractKeyPoints: jest.fn(() => ({
      topTopics: [],
      actionItems: [],
      decisions: [],
    })),
  },
}));

jest.mock('../src/renderer/services/autoCategorization', () => ({
  autoCategorizationService: {
    getCategorization: jest.fn(() => null),
  },
}));

describe('autoTaggingService reverse tag cache', () => {
  const originalLocalStorage = globalThis.localStorage;

  beforeAll(() => {
    Object.defineProperty(globalThis, 'localStorage', {
      value: new InMemoryStorage(),
      configurable: true,
      writable: true,
    });
  });

  afterAll(() => {
    Object.defineProperty(globalThis, 'localStorage', {
      value: originalLocalStorage,
      configurable: true,
      writable: true,
    });
  });

  beforeEach(() => {
    jest.resetModules();
    localStorage.clear();
  });

  it('returns sessions by tag and updates after tag changes', () => {
    const { autoTaggingService } = require('../src/renderer/services/autoTagging');

    autoTaggingService.updateTags('session-1', ['alpha', 'beta']);
    autoTaggingService.updateTags('session-2', ['beta']);

    expect(autoTaggingService.getConversationsByTag('beta').sort()).toEqual(['session-1', 'session-2']);
    expect(autoTaggingService.getConversationsByTag('alpha')).toEqual(['session-1']);

    autoTaggingService.updateTags('session-1', ['alpha']);

    expect(autoTaggingService.getConversationsByTag('beta')).toEqual(['session-2']);
    expect(autoTaggingService.getConversationsByTag('missing')).toEqual([]);
  });

  it('refreshes tag-session lookup when storage payload changes outside the service', () => {
    const { autoTaggingService } = require('../src/renderer/services/autoTagging');

    localStorage.setItem(
      'conversation_tags',
      JSON.stringify([
        { sessionId: 'session-a', tags: ['initial'], autoGenerated: false, taggedAt: 1 },
      ])
    );
    expect(autoTaggingService.getConversationsByTag('initial')).toEqual(['session-a']);

    localStorage.setItem(
      'conversation_tags',
      JSON.stringify([
        { sessionId: 'session-b', tags: ['updated'], autoGenerated: false, taggedAt: 2 },
      ])
    );

    expect(autoTaggingService.getConversationsByTag('initial')).toEqual([]);
    expect(autoTaggingService.getConversationsByTag('updated')).toEqual(['session-b']);
  });
});
